let purchaseData: string = JSON.stringify([
    {
        "ID": 10248,
        "Username": "VINET",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Reims",
    },
    {
        "ID": 10249,
        "Username": "TOMSP",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Münster",
    },
    {
        "ID": 10250,
        "Username": "HANAR",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Rio de Janeiro",
    },
    {
        "ID": 10251,
        "Username": "VICTE",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Lyon",
    },
    {
        "ID": 10252,
        "Username": "SUPRD",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Charleroi",
    },
    {
        "ID": 10253,
        "Username": "HANAR",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Rio de Janeiro",
    },
    {
        "ID": 10254,
        "Username": "CHOPS",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Bern",
    },
    {
        "ID": 10255,
        "Username": "RICSU",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Genève",
    },
    {
        "ID": 10256,
        "Username": "WELLI",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Resende",
    },
    {
        "ID": 10257,
        "Username": "HILAA",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "San Cristóbal",
    },
    {
        "ID": 10258,
        "Username": "ERNSH",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Graz",
    },
    {
        "ID": 10259,
        "Username": "CENTC",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "México D.F.",
    },
    {
        "ID": 10260,
        "Username": "OTTIK",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Köln",
    },
    {
        "ID": 10261,
        "Username": "QUEDE",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Rio de Janeiro",
    },
    {
        "ID": 10262,
        "Username": "RATTC",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Albuquerque",
    },
    {
        "ID": 10263,
        "Username": "ERNSH",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Graz",
    },
    {
        "ID": 10264,
        "Username": "FOLKO",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Bräcke",
    },
    {
        "ID": 10265,
        "Username": "BLONP",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Strasbourg",
    },
    {
        "ID": 10266,
        "Username": "WARTH",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Oulu",
    },
    {
        "ID": 10267,
        "Username": "FRANK",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "München",
    },
    {
        "ID": 10268,
        "Username": "GROSR",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Caracas",
    },
    {
        "ID": 10269,
        "Username": "WHITC",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Seattle",
    },
    {
        "ID": 10270,
        "Username": "WARTH",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Oulu",
    },
    {
        "ID": 10271,
        "Username": "SPLIR",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Lander",
    },
    {
        "ID": 10272,
        "Username": "RATTC",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Albuquerque",
    },
    {
        "ID": 10273,
        "Username": "QUICK",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Cunewalde",
    },
    {
        "ID": 10274,
        "Username": "VINET",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Reims",
    },
    {
        "ID": 10275,
        "Username": "MAGAA",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Bergamo",
    },
    {
        "ID": 10276,
        "Username": "TORTU",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "México D.F.",
    },
    {
        "ID": 10277,
        "Username": "MORGK",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Leipzig",
    },
    {
        "ID": 10278,
        "Username": "BERGS",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Luleå",
    },
    {
        "ID": 10279,
        "Username": "LEHMS",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Frankfurt a.M.",
    },
    {
        "ID": 10280,
        "Username": "BERGS",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Luleå",
    },
    {
        "ID": 10281,
        "Username": "ROMEY",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Madrid",
    },
    {
        "ID": 10282,
        "Username": "ROMEY",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Madrid",
    },
    {
        "ID": 10283,
        "Username": "LILAS",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Barquisimeto",
    },
    {
        "ID": 10284,
        "Username": "LEHMS",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Frankfurt a.M.",
    },
    {
        "ID": 10285,
        "Username": "QUICK",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Cunewalde",
    },
    {
        "ID": 10286,
        "Username": "QUICK",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Cunewalde",
    },
    {
        "ID": 10287,
        "Username": "RICAR",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Rio de Janeiro",
    },
    {
        "ID": 10288,
        "Username": "REGGC",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Reggio Emilia",
    },
    {
        "ID": 10289,
        "Username": "BSBEV",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "London",
    },
    {
        "ID": 10290,
        "Username": "COMMI",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Sao Paulo",
    },
    {
        "ID": 10291,
        "Username": "QUEDE",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Rio de Janeiro",
    },
    {
        "ID": 10292,
        "Username": "TRADH",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Sao Paulo",
    },
    {
        "ID": 10293,
        "Username": "TORTU",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "México D.F.",
    },
    {
        "ID": 10294,
        "Username": "RATTC",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Albuquerque",
    },
    {
        "ID": 10295,
        "Username": "VINET",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Reims",
    },
    {
        "ID": 10296,
        "Username": "LILAS",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Barquisimeto",
    },
    {
        "ID": 10297,
        "Username": "BLONP",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Strasbourg",
    },
    {
        "ID": 10298,
        "Username": "HUNGO",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Cork",
    },
    {
        "ID": 10299,
        "Username": "RICAR",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Rio de Janeiro",
    },
    {
        "ID": 10300,
        "Username": "MAGAA",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Bergamo",
    },
    {
        "ID": 10301,
        "Username": "WANDK",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Stuttgart",
    },
    {
        "ID": 10302,
        "Username": "SUPRD",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Charleroi",
    },
    {
        "ID": 10303,
        "Username": "GODOS",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Sevilla",
    },
    {
        "ID": 10304,
        "Username": "TORTU",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "México D.F.",
    },
    {
        "ID": 10305,
        "Username": "OLDWO",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Anchorage",
    },
    {
        "ID": 10306,
        "Username": "ROMEY",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Madrid",
    },
    {
        "ID": 10307,
        "Username": "LONEP",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Portland",
    },
    {
        "ID": 10308,
        "Username": "ANATR",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "México D.F.",
    },
    {
        "ID": 10309,
        "Username": "HUNGO",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Cork",
    },
    {
        "ID": 10310,
        "Username": "THEBI",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Portland",
    },
    {
        "ID": 10311,
        "Username": "DUMON",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Nantes",
    },
    {
        "ID": 10312,
        "Username": "WANDK",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Stuttgart",
    },
    {
        "ID": 10313,
        "Username": "QUICK",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Cunewalde",
    },
    {
        "ID": 10314,
        "Username": "RATTC",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Albuquerque",
    },
    {
        "ID": 10315,
        "Username": "ISLAT",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Cowes",
    },
    {
        "ID": 10316,
        "Username": "RATTC",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Albuquerque",
    },
    {
        "ID": 10317,
        "Username": "LONEP",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Portland",
    },
    {
        "ID": 10318,
        "Username": "ISLAT",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Cowes",
    },
    {
        "ID": 10319,
        "Username": "TORTU",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "México D.F.",
    },
    {
        "ID": 10320,
        "Username": "WARTH",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Oulu",
    },
    {
        "ID": 10321,
        "Username": "ISLAT",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Cowes",
    },
    {
        "ID": 10322,
        "Username": "PERIC",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "México D.F.",
    },
    {
        "ID": 10323,
        "Username": "KOENE",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Brandenburg",
    },
    {
        "ID": 10324,
        "Username": "SAVEA",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Boise",
    },
    {
        "ID": 10325,
        "Username": "KOENE",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Brandenburg",
    },
    {
        "ID": 10326,
        "Username": "BOLID",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Madrid",
    },
    {
        "ID": 10327,
        "Username": "FOLKO",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Bräcke",
    },
    {
        "ID": 10328,
        "Username": "FURIB",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Lisboa",
    },
    {
        "ID": 10329,
        "Username": "SPLIR",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Lander",
    },
    {
        "ID": 10330,
        "Username": "LILAS",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Barquisimeto",
    },
    {
        "ID": 10331,
        "Username": "BONAP",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Marseille",
    },
    {
        "ID": 10332,
        "Username": "MEREP",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Montréal",
    },
    {
        "ID": 10333,
        "Username": "WARTH",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Oulu",
    },
    {
        "ID": 10334,
        "Username": "VICTE",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Lyon",
    },
    {
        "ID": 10335,
        "Username": "HUNGO",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Cork",
    },
    {
        "ID": 10336,
        "Username": "PRINI",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Lisboa",
    },
    {
        "ID": 10337,
        "Username": "FRANK",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "München",
    },
    {
        "ID": 10338,
        "Username": "OLDWO",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Anchorage",
    },
    {
        "ID": 10339,
        "Username": "MEREP",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Montréal",
    },
    {
        "ID": 10340,
        "Username": "BONAP",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Marseille",
    },
    {
        "ID": 10341,
        "Username": "SIMOB",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Kobenhavn",
    },
    {
        "ID": 10342,
        "Username": "FRANK",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "München",
    },
    {
        "ID": 10343,
        "Username": "LEHMS",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Frankfurt a.M.",
    },
    {
        "ID": 10344,
        "Username": "WHITC",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Seattle",
    },
    {
        "ID": 10345,
        "Username": "QUICK",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Cunewalde",
    },
    {
        "ID": 10346,
        "Username": "RATTC",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Albuquerque",
    },
    {
        "ID": 10347,
        "Username": "FAMIA",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Sao Paulo",
    },
    {
        "ID": 10348,
        "Username": "WANDK",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Stuttgart",
    },
    {
        "ID": 10349,
        "Username": "SPLIR",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Lander",
    },
    {
        "ID": 10350,
        "Username": "LAMAI",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Toulouse",
    },
    {
        "ID": 10351,
        "Username": "ERNSH",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Graz",
    },
    {
        "ID": 10352,
        "Username": "FURIB",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Lisboa",
    },
    {
        "ID": 10353,
        "Username": "PICCO",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Salzburg",
    },
    {
        "ID": 10354,
        "Username": "PERIC",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "México D.F.",
    },
    {
        "ID": 10355,
        "Username": "AROUT",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Colchester",
    },
    {
        "ID": 10356,
        "Username": "WANDK",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Stuttgart",
    },
    {
        "ID": 10357,
        "Username": "LILAS",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Barquisimeto",
    },
    {
        "ID": 10358,
        "Username": "LAMAI",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Toulouse",
    },
    {
        "ID": 10359,
        "Username": "SEVES",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "London",
    },
    {
        "ID": 10360,
        "Username": "BLONP",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Strasbourg",
    },
    {
        "ID": 10361,
        "Username": "QUICK",
        "E-mail": "kolyo@abv.bg",
        "Full Name": "Cunewalde",
    }
]);

export const orderDataSource: Object[] = JSON.parse(purchaseData, (field: any, value: any) => {
   // IF DATE (in this format 'kolyo@abv.bg') -> FORMAT TO DATE OBJECT (so it can be displayed on the datatable)
   if (typeof value === 'string' && /^(\d{4}\-\d\d\-\d\d([tT][\d:\.]*){1})([zZ]|([+\-])(\d\d):?(\d\d))?$/.test(value)) {
      let dupValue: any = value;
      let arr: any = dupValue.split(/[^0-9]/);
      let arg: any = parseInt(arr[4], 10);
      let arg1: any = parseInt(arr[5], 10);

      value = new Date(parseInt(arr[0], 10), parseInt(arr[1], 10) - 1, parseInt(arr[2], 10), parseInt(arr[3], 10), arg, arg1);
    }
    return value;
});